name: "Builds on commit"
on: [push]

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      
      - name: setup Bun
        uses: oven-sh/setup-bun@v1.1.1
        with:
          bun-version: canary
      
      - name: Rust cache
        uses: Swatinem/rust-cache@v2.7.3
        with:
          workspaces: './src-tauri -> target'
      
      - name: install Rust stable
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
      
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      
      - name: install frontend dependencies
        run: bun install # change this to npm or pnpm depending on which one you use
      
      - uses: tauri-apps/tauri-action@v0
        with:
          tauriScript: bun run tauri
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: All artifacts
          path: |
            ${{ runner.os }}-bundle/
            '/home/runner/work/cliticlick/cliticlick/src-tauri/target/release/bundle/*'

      - name: Prepare bundle directory for Windows
        if: matrix.platform == 'windows-latest'
        run: |
          mkdir ${{ runner.os }}-bundle
          mv '/Users/runner/work/cliticlick/cliticlick/src-tauri/target/release/bundle/'* ./${{ runner.os }}-bundle/

      - name: Prepare bundle directory for macOS
        if: matrix.platform == 'macos-latest'
        run: |
          mkdir ${{ runner.os }}-bundle
          mv '/home/runner/work/cliticlick/cliticlick/src-tauri/target/release/bundle/'* ./${{ runner.os }}-bundle/

      - name: Prepare bundle directory for Ubuntu
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          mkdir ${{ runner.os }}-bundle
          mv '/home/runner/work/cliticlick/cliticlick/src-tauri/target/release/bundle/'* ./${{ runner.os }}-bundle/
