name: "Builds on commit"
on: [push]

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      
      - name: setup Bun
        uses: oven-sh/setup-bun@v1.1.1
        with:
          bun-version: canary
      
      - name: install Rust stable
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
      
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      
      - name: install frontend dependencies
        run: bun install # change this to npm or pnpm depending on which one you use
      
      - uses: tauri-apps/tauri-action@v0
        with:
          tauriScript: bun run tauri
      
      - name: Upload artifact for Windows
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Windows builds
          path: D:\a\cliticlick\cliticlick\src-tauri\target\release\bundle\*
          
      - name: Upload artifact for macOS
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v4.3.1
        with:
          name: macOS builds
          path: /Users/runner/work/cliticlick/cliticlick/src-tauri/target/release/bundle/*
          
      - name: Upload artifact for Ubuntu
        if: matrix.platform == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Ubuntu builds
          path: /home/runner/work/cliticlick/cliticlick/src-tauri/target/release/bundle/*
